services:
  test_api:
    build:
      context: flask
      dockerfile: Dockerfile
    secrets:
      - db_password
    environment:
      - FLASK_ENV=testing
      - FLASK_DEBUG=1
    command: "python -m unittest run_tests"

secrets:
  db_password:
    file: secrets/db_password.txt
    
