version: '3.3'
services:
  db: 
    image: "mysql:8.3"
    restart: always
    environment:
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_USER=api
      - MYSQL_DATABASE=nawas
    volumes:
      - ./src/sql:/opt/scripts/
      - mysql:/var/lib/mysql
    secrets:
      - mysql_password
  api:
    depends_on:
      - db
    build:
      context: flask
      dockerfile: Dockerfile
    restart: always
    secrets:
      - mysql_password
    bind:
       - 8000:8000
volumes:
  mysql:
secrets:
  mysql_password:
    environment: MYSQL_PASSWORD

    
