services:
  db: 
    image: "mysql:8.3"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_USER=api
      - MYSQL_DATABASE=nawas
    volumes:
      - ./src/sql:/opt/scripts/
      - mysql:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
  api:
    depends_on:
      - db
    build:
      context: flask
      dockerfile: Dockerfile
    restart: always
    environment:
      - FLASK_ENV=production
    secrets:
      - db_password
    ports:
       - "8000:8000"
volumes:
  mysql:
secrets:
  db_password:
    file: secrets/db_password.txt
  db_root_password:
    file: secrets/db_root_password.txt

    
