services:
  db: 
    image: "mysql:8.3.0"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=nawas
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost']
      timeout: 20s
      interval: 30s
      retries: 10
      start_period: 30s
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d/
      - mysql:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    networks:
      backnet:
        ipv4_address: 172.16.238.3
  api:
    depends_on:
      db:
        condition: service_healthy
        restart: true
    build:
      context: flask
      dockerfile: Dockerfile
    restart: always
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=1
    secrets:
      - db_password
    ports:
       - "8000:8000"
    networks:
      backnet:
        ipv4_address: 172.16.238.2
volumes:
  mysql:
secrets:
  db_root_password:
    file: secrets/db_root_password.txt
  db_password:
    file: secrets/db_password.txt
networks:
  backnet:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/29"
    
