services:
  test_api:
    build:
      context: flask
      dockerfile: Dockerfile
    restart: always
    secrets:
      - db_password
    environment:
      - FLASK_ENV=testing
    command: "python -m unittest discover -s tests"

secrets:
  db_password:
    file: secrets/db_password.txt
    
