
-- BASIC MODEL
-- basic data structures for fundamental elements

CREATE DATABASE IF NOT EXISTS nawas;
USE nawas;

CREATE TABLE IF NOT EXISTS tenant (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name nvarchar(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS asn (
	ASN INT UNSIGNED NOT NULL PRIMARY KEY,
	tenant SMALLINT UNSIGNED NOT NULL,

	FOREIGN KEY (tenant)
	  REFERENCES tenant(id)
		ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS prefix (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ASN INT UNSIGNED NOT NULL,
	cidr nvarchar(40) NOT NULL UNIQUE,

	FOREIGN KEY (ASN)
	  REFERENCES asn(ASN)
		ON UPDATE CASCADE ON DELETE RESTRICT
);

-- CHANGE TABLES
-- track changes to the prefix tables, should be provided by the API

CREATE TABLE IF NOT EXISTS prefix_changes (
	prefix_id INT UNSIGNED NOT NULL,
	timestamp TIMESTAMP NOT NULL,
	added BOOL DEFAULT false,
	removed BOOL DEFAULT false,
	
  PRIMARY KEY (prefix_id, timestamp)
--	CONSTRAINT pc_changed CHECK ( added XOR removed ) TODO: nice to have
);
